### ISSUE TITLE
The default specify quota is not 5120 when creating a new file share during uploading files

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-azurestorage#1147]
**OS:** Windows 10
**Build:** 20220901.11

**Repro Steps:**

1. Create a new storage account -> F1 -> Azure Storage: Upload Files... -> Select a file -> Select "File Share" -> Select "+ Create new File Share..." -> Type a name -> Press Enter.
2. Check whether the Specify quota is 5120 by default.

**Expect:**
The default specify quota is 5120.
![image](https://user-images.githubusercontent.com/107091828/188072908-1175eb1e-aa88-49d1-b992-21b19e108be1.png)

**Actual:**
The default specify quota is the same as the File Share name.
![image](https://user-images.githubusercontent.com/107091828/188072838-e4407715-d49b-4e05-8960-1fe4420ab095.png)

**More Info:**
This issue also reproduces when creating a new file share during executing "Upload Folder..." command.

**Comment by motm32** [comment]
This issue is caused by the cache values being mixed up since there are multiple `showInputBox` calls being made in the same wizard step. See [FileShareGroupTreeItem](https://github.com/microsoft/vscode-azurestorage/blob/main/src/tree/fileShare/FileShareGroupTreeItem.ts#:~:text=public%20async%20createChildImpl(context%3A%20ICreateChildImplContext)%3A%20Promise%3CFileShareTreeItem%3E).

**Comment by alexweininger** [comment]
Caused by https://github.com/microsoft/vscode-azurestorage/pull/1084

**Comment by MicroFish91** [comment]
Ahh I see, it looks like involving a wizard means adding a cached value check behind the scenes:

![Screen Shot 2022-09-06 at 10 33 04 AM](https://user-images.githubusercontent.com/40250218/188702055-948f8729-be54-4e57-86ea-d2e749196ab3.png)

Could we do something like this to fix this issue:

`inputBox.value = options.value || wizard?.getCachedInputBoxValue() || '';`

Or do you still want to wait on a separate change related to v2?

**Comment by alexweininger** [comment]
> Could we do something like this to fix this issue:
> 
> `inputBox.value = options.value || wizard?.getCachedInputBoxValue() || '';`
> 
> Or do you still want to wait on a separate change related to v2?

That would break a lot of wizards since it would always override the cached value with whatever the initial value was.

We will need to discuss as a team. The correct solution could be to create a new context for these extra prompts in a wizard step. Or to base the cache key on something more unique than just the wizard step.
