### ISSUE TITLE
Delete many support for Storage Accounts

### ISSUE THREAD

**Issue by MicroFish91** [microsoft/vscode-azurestorage#1165]
Feature/Enhancement idea.... 

Would be nice to be able to delete multiple storage accounts in one go (there was a similar issue posted a couple years back for doing this through `command palette`, but I'm primarily interested in being able to quickly do this from the tree view)

**Comment by bwateratmsft** [comment]
We went through some related exercises in the Docker extension a while back. One of the challenges we faced there was that, when multi-selecting and executing a command, only the context value of the right-clicked node is considered, for the purposes of deciding what commands to show.

Let me give an example. In the Docker extension we allow many different actions that can be taken on containers--start, stop, remove, etc. Some of these are only valid in certain container states (e.g. you can't stop a stopped container, or start a running one, etc.). If you multi-select a set of several containers in different states, and right-click a running one, the commands for running containers will be shown (i.e. stop)--even if others in the selection are stopped.

The net result is that we need to do some filtering to take out nodes we'd be performing invalid actions on. That happens [here](https://github.com/microsoft/vscode-docker/blob/main/src/utils/multiSelectNodes.ts). Note, this also handles prompting when the command is executed from the palette instead of tree item context menu.

**Comment by nturinski** [comment]
Closing as too dangerous. 🛡️
