### ISSUE TITLE
[Linux]Clicking 'Open Blob Container in Storage Explorer' pops up a warning when Storage Explorer is opened

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/vscode-azurestorage#140]
Repro Steps:
1. Make sure Storage Explorer is opened.
2. Right click one blob container and select 'Open Blob Container in Storage Explorer'.

Expect:
The selected blob container can be opened in Storage Explorer successfully.

Actual:
Pop up an error "Can't find Storage Explorer".
![error](https://user-images.githubusercontent.com/34729022/39859377-3174d45a-5429-11e8-8cd7-6513e6406d15.png)

More info:
No response after clicking 'Download' in the dialog.

**Comment by PrashanthCorp** [comment]
Related to an existing issue on Azure Storage Explorer - the deep link feature does not work on Linux.

**Comment by PrashanthCorp** [comment]
Mac: 
I could not repro the issue on Mac. If I click Download, I'm directed to the Storage Explorer landing page. Clicking browse allows me to pick the location of the file. 

Linux: 
Browse opens up a dialog, but the StorageExplorer executable is not visible due to the filter on the fileType, here: 
https://github.com/Microsoft/vscode-azurestorage/blob/857d35df8fab1d66369dd9d12ffa0203bbcd4310/src/storageExplorerLauncher/macOSStorageExplorerLauncher.ts#L91
The workaround (manually setting a path in the settings) tries to open the wrong path. Fixing that, the deep link issue in Linux further prevents Storage Explorer from opening. 
We can failry say that this feature is not yet supported on Linux.
