### ISSUE TITLE
Automatically suggest dist for vue, build for angular and out (if exist) for website deployment source

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode-azurestorage#176]

**Comment by PrashanthCorp** [comment]
Is it predominant for the builds to be written to those mentioned? I'd like to know how often users leave the build directories as is? I also see two more approaches: 
1. Instead of trying to figure out if the project is react, angular, or vue, we show all of dist, build and out that exist
2. Add a setting for them to set the default deployment folder. Users who have overwritten the `outDir` , for example [here](https://stackoverflow.com/questions/37348045/how-to-change-the-dist-folder-path-in-angular-cli-after-ng-build).

**Comment by StephenWeatherford** [comment]
cc @fiveisprime 

The intention was to simply put them into the dropdown picker for folders so they can easily select it.  Yes, I think it makes sense to simply show all of dist, build and out that exist.

As for suggestion 2, I'd have to play with our behavior again, but it probably wouldn't be bad to do what functions/appservice do, but I think suggestion 1 is most important and can be done quite easily.

**Comment by PrashanthCorp** [comment]
Closing via merged PR.
