### ISSUE TITLE
Prompt for folder before destination account when deploying

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode-azurestorage#187]
It's currently inconsistent with the other extensions with deployment functionality.

**Comment by EricJizbaMSFT** [comment]
@fiveisprime this probably needs further discussion. @jdneo recently flipped the order in app service (See https://github.com/Microsoft/vscode-azureappservice/pull/456). I don't have a strong preference, but he did that because Java deploys a war file instead of a folder. If he asks for the app service first, he can auto-detect if it's Java and ask for the correct file/folder type second.

**Comment by jdneo** [comment]
Yes the change is introduced by me. The reason is just as @EricJizbaMSFT said. So far I cannot find a suitable way to determine which kind of deployment can be used before a target Web App is selected. Anyway, I'm willing to change it back if we can figure out the right solution. Let's discuss. 😄

**Comment by fiveisprime** [comment]
I'll let this sit for a few weeks and see if any customers report it.

**Comment by StephenWeatherford** [comment]
I actually set it up this way only because we can't currently enable an account for website deployment from the extension, and I didn't want users to go through browsing for a directory and then have to cancel when we tell them to enable the account first.  Hopefully we'll be able to enable ourselves soon.
