### ISSUE TITLE
Browse to Static Website should not be available for storage accounts where websites are not enabled

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode-azurestorage#200]
But this will require changing the contextValue of the node and therefore is not a low-risk change.

**Comment by wwlorey** [comment]
Selecting "Browse Static Website" if hosting is disabled throws this error which prompts to configure hosting:

<img width="383" alt="Screen Shot 2020-10-14 at 10 39 30 AM" src="https://user-images.githubusercontent.com/22795803/96025184-a4f5d180-0e09-11eb-9c48-9f4ec998de37.png">

Closing since this this message should clear up any confusion about why browsing to the site didn't work.
