### ISSUE TITLE
Time out when uploading a project with a lot of files

### ISSUE THREAD

**Issue by PrashanthCorp** [microsoft/vscode-azurestorage#352]
See #334, #338, #339, #342 , #373

**Comment by StephenWeatherford** [comment]
#342 shows the timeout while deleting a file (so at least in this case not due to the size of the file).  We should make sure we've got automatic retries set up, although I thought that was the default.

**Comment by viljamis** [comment]
Would love to see a fix for this as right now this makes the whole extension pretty much completely unusable. 

Not sure what’s causing it, but we always get either ETIMEDOUT or ESOCKETTIMEDOUT which forces us to use Azure Pipelines automation or something similar to deploy even the most simplest prototypes to Azure Storage. 

This also doesn’t just affect projects with lots of files since this happens all the time even in the small projects with just under 20 assets.

**Comment by StephenWeatherford** [comment]
@viljamis Thanks for the extra info.  We'll look into it.
