### ISSUE TITLE
Handle remote environments better

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode-azurestorage#387]
I have the storage extension installed in my remote (WSL) and opening a container in the file explorer launches a new VS Code instance that's not connected to the remote.

Is there a way to determine if the environment is remote and open the container in the same way?
Can the container be opened in the same window and retain the remote setup?

**Comment by EricJizbaMSFT** [comment]
So Will fixed https://github.com/microsoft/vscode-azurestorage/issues/434, which we thought might help, but it doesn't. I had an ssh window open, tried all three options, and all resulted in losing the remote connection.

@fiveisprime can you define more of the expected behavior here? The workspace itself is obviously not a folder in WSL or on the SSL machine, so nothing in the file view should be related to remote. Is this all about the terminal?

**Comment by EricJizbaMSFT** [comment]
Actually the "Add to Workspace" option fails with this error:
![Screen Shot 2020-01-08 at 10 33 15 AM](https://user-images.githubusercontent.com/11282622/72005409-6429b600-3202-11ea-8b45-982735bd5058.png)

**Comment by EricJizbaMSFT** [comment]
Filed an issue on VS Code: https://github.com/microsoft/vscode/issues/88301

**Comment by fiveisprime** [comment]
It has nothing to do with the terminal, rather whether the extension is available.

**Comment by alexweininger** [comment]
Issue no longer reproduces. Probably fixed by https://github.com/microsoft/vscode/issues/88301
