### ISSUE TITLE
Support `FileSystemProvider.watch` for blobs and file shares

### ISSUE THREAD

**Issue by EricJizbaMSFT** [microsoft/vscode-azurestorage#435]
Right now it throws "Method not implemented"

**Comment by EricJizbaMSFT** [comment]
Might even be root cause of https://github.com/microsoft/vscode-azurestorage/issues/432

**Comment by PrashanthCorp** [comment]
Do you have a repro for this @monalgarg @EricJizbaMSFT ?

**Comment by EricJizbaMSFT** [comment]
@PrashanthCorp just look at the documentation for the API: https://github.com/microsoft/vscode/blob/master/src/vs/vscode.d.ts#L5669

**Comment by PrashanthCorp** [comment]
I already did. 

The samples also tells us returning an empty disposable is okay: 
https://github.com/microsoft/vscode-extension-samples/blob/master/fsprovider-sample/src/fileSystemProvider.ts#L212

I'm asking a repro because running through #432 with master still doesn't surface this error in problems or output :) 
![image](https://user-images.githubusercontent.com/30420973/62727849-37f9d700-b9cf-11e9-8ce4-188c50dcb858.png)

![image](https://user-images.githubusercontent.com/30420973/62727879-434d0280-b9cf-11e9-9a0f-8b4b2aa6bab8.png)

I don't have as much context into the code here, so I'm asking what I'm missing. Without an error I can see, I can't verify any fix I make. :)

**Comment by EricJizbaMSFT** [comment]
The crux of this bug is that "Method not implemented" is not acceptable for production code. There's nothing in the docs that implies this method is optional (samples are meant to be simple and don't count as docs). Whoever works on this bug needs to research the method and create their own repro steps to verify before and after their fix. This is exactly what Monal did as she implemented each method on `FileSystemProvider`.

 I have the same information as you do - just the docs on the API (look at _all_ watch related methods, including `watch`, `onDidChangeFile`, and `createFileSystemWatcher`).

**Comment by EricJizbaMSFT** [comment]
For future reference, this rough code can be used to test watch:
```typescript
const watcher = workspace.createFileSystemWatcher('**');
watcher.onDidChange(e => {
    console.log(`CHANGE: ${e.fsPath}`);
});
watcher.onDidCreate(e => {
    console.log(`CREATE: ${e.fsPath}`);
});
watcher.onDidDelete(e => {
    console.log(`DELETE: ${e.fsPath}`);
});
```

And it should show output similar to this:
```
CREATE: /test/a
CHANGE: /test/a.txt
CREATE: /test/aaa
CREATE: /test/aaa/bbb
CREATE: /test/aaa/bbb/c.txt
DELETE: /test/aaa/bbb/c.txt
```
