### ISSUE TITLE
Creating a new file can wipe contents of another file with same name if not in same batch

### ISSUE THREAD

**Issue by monalgarg** [microsoft/vscode-azurestorage#436]
**Repro Steps:**

1. Under a new file share -> create a file with the name "z.txt" and "a.txt"
2. Write some content in "z.txt"
3. In fileShareNode.ts, change the maxResults under the method listFiles to 1
4. Open this file share in File Explorer -> should only see "a.txt"
5. Create a new file "z.txt"

**Actual:**
Deletes the contents of the previous "z.txt" file and this file does not show up in the File Explorer.

**Suggestion:**
Show an error to the user saying this action would overwrite another file.

**Comment by StephenWeatherford** [comment]
The best way to handle this is to set up the options.accessConditions to not allow writing over an existing blob, rather than trying to check yourself if the blob already exists (see generateIfNotExistsCondition).

**Comment by EricJizbaMSFT** [comment]
I looked into this and wanted to document what I found while it was fresh in my head. Unfortunately the VS Code api just doesn't work well with pagination. For _loaded_ files, VS Code will ensure the user doesn't overwrite an existing file:
![Screen Shot 2019-12-11 at 5 27 39 PM](https://user-images.githubusercontent.com/11282622/70674664-8d731880-1c3b-11ea-8353-4a95c6fb4a48.png)

If a file has _not_ been loaded, VS Code obviously can't detect the conflict and ends up calling our `writeFile` method with options `{"create":true,"overwrite":true}`. The options alone imply we should overwrite an existing file (but obviously we don't want to do that). To make matters even worse, the exact same options are passed to `writeFile` after I modify and save an existing file. In this case we _do_ want to overwrite, but the problem is we have no way to differentiate the two scenarios.
