### ISSUE TITLE
Could not retrieve the primary web endpoint for "project"

### ISSUE THREAD

**Issue by andreslon** [microsoft/vscode-azurestorage#439]
Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureStorage.deployStaticWebsite
Error type: Error
Error Message: Could not obtain the primary web endpoint for "project"

Version: 0.7.1
OS: darwin

**Comment by PrashanthCorp** [comment]
Does this error repro consistently? 

It looks like our API call did not get any endpoints from the storage account associated with your `project` app. Can you check in the portal if the endpoints are shown (go to the storage account's blade, and look under "properties")
![image](https://user-images.githubusercontent.com/30420973/63059494-6f232900-bea4-11e9-8eb0-ef4b64a58763.png)

**Comment by v-dantch** [comment]
Hi Prashanth, this issue also reproduces for us when signing in with Azure China & Azure Germany accounts. Due to there is even no "Static website" item in Portal.
And the answer for above question -- no endpoints are shown in the Properties item. Please get the details from below:
![image](https://user-images.githubusercontent.com/34729092/64152103-79f72b00-ce5e-11e9-8e61-5fbca4bb06d2.png)
