### ISSUE TITLE
[blob] Mimic azure storage behavior when creating new folders in file explorer

### ISSUE THREAD

**Issue by monalgarg** [microsoft/vscode-azurestorage#442]
Azure Storage prevents users from creating folders that contain '/', '\\' or are empty strings. Users are allowed to create files with '/', this just creates folders and subfolders. However, Azure Storage treats '/' and '\\' similarly and will create folders and subfolders accordingly.

**Comment by PrashanthCorp** [comment]
Verify: replacing '\\' with '/' solves the issue.

**Comment by wwlorey** [comment]
VS Code will only create nested directories for paths that use the `/` separator.

For a path like `dir1\dir2\my_blob`, replacing `\` with `/` doesn't work because when VS Code calls `AzureStorageFS.createDirectory`, it expects to find a new directory with the URI it passed in

![Screen Shot 2020-01-15 at 4 57 30 PM](https://user-images.githubusercontent.com/22795803/72484136-26a3ca80-37b8-11ea-9a95-f64358f5a053.png)
