### ISSUE TITLE
Large blobs uploaded from within window.WithProgress are corrupt

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurestorage#537]
**OS**: Win10 & Mac
**Build Version:** [20191216.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=13157&view=results)
**Regression**: Previous Release (0.7.2)

**Repro Steps:**
1. Create a new storage account -->Right click the new created storage account  --> Select "Deploy to Static Website...".
2. Check the website after deploying.

**Expect:**
The website displays well.
![image](https://user-images.githubusercontent.com/34729092/70977931-d4ed1f00-20e9-11ea-956c-964f7e0b73d0.png)

**Actual:**
Display a blank website.
![image](https://user-images.githubusercontent.com/34729092/70977905-c999f380-20e9-11ea-814e-6a6116ea8766.png)

**Comment by wwlorey** [comment]
For blobs of a requisite size, the first chunk of each blob would be appended repeatedly leading to a corrupted result. The file size, metadata, and properties of corrupt blobs were identical to blobs uploaded using the last working version of the extension. This caused the test website to not render properly.

This problem is related to how we used `window.withProgress`. It's unclear what exactly the problem is - it could be a bug on Azure or it could be related to how we debounce notification progress reporting. Removing `window.withProgress` from the upload logic fixed the issue (#540)
