### ISSUE TITLE
The rule of naming resource group is unfriendly when creating a basic storage account

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurestorage#681]
**OS:** Mac
**Build Version:** 20200531.1

**Repro Steps:**

1. Create a basic storage account with name "test".
2. Delete this storage account.
3. Create a basic "test" storage account again.
4. Check the output log.

**Expect:**
The log should show "Creating resource group  '**test1**' in location 'westus'...".

**Actual:**
The log shows "Creating resource group  '**test2**' in location 'westus'...".
![image](https://user-images.githubusercontent.com/62053665/83388191-9ab9d480-a420-11ea-9954-0683fc829574.png)

**Comment by nturinski** [comment]
Hi @v-mengwe

Thanks for reporting this, but this is by-design.  Rather than reusing the resource group, we just create a new one and add a number to it so that all of the resources that we create are in one group.  This is only for basic create where we want to hide some of the details from the user because they are confusing.

**Comment by v-mengwe** [comment]
@nturinski Thanks for your update.
I know your means, but I think the new created resource group should add a number which start with 1, rather than start with 2. Such as we have a resource group name with "test", the next resource group name should be "test1".

**Comment by nturinski** [comment]
@v-mengwe Oh, okay.  Sorry for misunderstanding!  I'll reopen and discuss with the team.

**Comment by nturinski** [comment]
Thanks for reporting, but after discussing it with the team, we are happy with the way it currently is.
