### ISSUE TITLE
No longer able to upload to storage accounts - Upload Error - Reason: Write EPIPE

### ISSUE THREAD

**Issue by jamesbarber** [microsoft/vscode-azurestorage#700]
Hey there,

I'm unable to deploy to my Azure static storage accounts anymore via the VScode plugin. When I deploy, the existing files on the storage container are deleted (as normal), but the upload of the new files (which is now incredibly slow) gets stuck around 4-5% through before completely failing and giving me this error:

I've checked the Azure Storage output and there isn't a particular file or file type that's causing the issue. I'm using Gatsby to create my static site.

Does this occur consistently? **YES**
Repro steps:

1. Build my deployable Gatsby production folder (/public)
2. 'Deploy to Static Website'
3. Select static website
4. Wait while deletion and upload takes place
5. Error hit during upload

Action: azureStorage.deployStaticWebsite
Error type: Error
Error Message: Error uploading "../MY_GITHUB_REPO/public/RANDOM_FILE.ext": request to https://MY_STATIC_WEBSITE.blob.core.windows.net/%24web/RANDOM_FILE.ext failed, reason: write EPIPE 

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:157:132413
rejected extension.bundle.js:157:131773
processTicksAndRejections task_queues.js:85:5
```

</details>

OS: **macOS Catalina**
OS Release: **10.15.5**
Product: **Visual Studio Code**
Product Version: **1.47.0**
Azure Storage Extension Version: **0.9.0**
Node Version: **6.14.4**
Language: **en**

**Comment by nturinski** [comment]
Hi @jamesbarber 
Thanks for reporting.  Do you know if this started happening after updating to 0.9.0 or did it just start happening out of nowhere?  Trying to figure out if we caused a regression (though our last Storage release was in March so that seems unlikely.)

I doubt that our transfer would have issues with .ext files, but is that consistently the same file that fails uploading? 

Also, Azure has released a new resource called Static Web Apps that might be easier to use than Storage for your deployment scenario.  The extension can be found [here](https://github.com/microsoft/vscode-azurestaticwebapps) with some documentation [here](https://docs.microsoft.com/en-us/azure/static-web-apps/)

**Comment by jamesbarber** [comment]
Hey @nturinski 

Cheers for you reply. The error started happening out of the blue, which I know is incredibly unhelpful sorry! And I'm still getting it. I've been on v0.9.0 for a while now so nothing to do with that, as you say. I'm using "RANDOM_FILE.ext" in that error message as an example of a file - just forget the '.ext', the upload breaks on random file types, no anomalies to report.

I'm going to do some more digging into the Azure side of things and see if there's something wrong with my static website at that end. Will update 👍

**Comment by jamesbarber** [comment]
And just like that it's working again..

Things that happened leading up to fix (even if highly unlikely to be related):

 - Updated VS Code to v1.47
 - Installed macOS Big Sur Beta 2

Weird one.
