### ISSUE TITLE
[Suggestion] Add a confirmation dialog to confirm the deployment

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurestorage#710]
**OS:** Windows 10
**Build Version:** 20200720.1

**Repro Steps:**
1. Create a basic storage account.
2. Right click this storage account and execute "Deploy to static website via Azure storage".

**Actual:**
It will deploy directly without any confirmation dialog.

**Suggestion:**
Add a confirmation dialog to confirm the deployment, like the below screen.
![image](https://user-images.githubusercontent.com/45614674/88042042-def26700-cb7d-11ea-8d7a-4413717f20de.png)

**Comment by nturinski** [comment]
This is because the storage account you are deploying to has an empty $web directory (the location it's being deployed to.)  If you have files in that directory, you will get a prompt to confirm deployment.

![image](https://user-images.githubusercontent.com/5290572/88231693-7eb8ff00-cc29-11ea-96fc-8e16c0a55008.png)
