### ISSUE TITLE
Uploading multiple folders is not supported

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestorage#794]
**OS:** All
**Build Version:** 20200911.6

**Repro Steps:**

1. F1 --> Select "Upload Folder...".
2. Check the result.

**Expect:**
Select multiple folders to upload at once.

**Actual:** 
Only select one folder to upload at once.

**More Info:**
This issue doesn't reproduce when uploading multiple files.

**Comment by wwlorey** [comment]
This is by design - we're matching what Storage Explorer does with "Upload Folder..." and "Upload Files...":

<img width="154" alt="Screen Shot 2020-09-11 at 10 20 57 AM" src="https://user-images.githubusercontent.com/22795803/92954571-83738580-f418-11ea-9e30-75113e9750e8.png">

While multiple folder uploads aren't supported in the Azure Tree, they are possible using the "Upload to Azure Storage..." command in the Explorer. They're supported in this case because users can select any number of files/folders at the same time in that view. Which is something we don't have control over in the extension.

<img width="500" alt="Screen Shot 2020-09-11 at 10 26 27 AM" src="https://user-images.githubusercontent.com/22795803/92955049-52e01b80-f419-11ea-838d-0ad4556fa6c3.png">
