### ISSUE TITLE
There is no command "Attached Storage Accounts" when executing "Copy Connection String" command

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurestorage#799]
**OS:** All
**Build Version:** 20200911.6

**Repro Steps:**
F1 --> Type and select "Azure Storage: Copy Connection String" --> Check the list.

**Expect:**
There is a command "Attached Storage Accounts", such as:
![image](https://user-images.githubusercontent.com/62053665/92905397-31e9eb80-f456-11ea-9fea-71477d90caf5.png)

**Actual:**
There is no command "Attached Storage Accounts".
![image](https://user-images.githubusercontent.com/62053665/92901120-d23e1100-f452-11ea-93c8-a52b58b04bb9.png)

**More Info:**
There is "Copy Connection String" command when right clicking the Local Emulator/Attached storage account.
![image](https://user-images.githubusercontent.com/62053665/92905263-1979d100-f456-11ea-88ab-4b8194d33b39.png)

**Comment by nturinski** [comment]
Copy Connection strings is primarily a scenario for Azure storage accounts rather than attached (since you probably attached it with a connection string).  Adding this to the cmd palette would add an extra prompt which is annoying for users.  We think the right-click context menu should suffice for most users.
