### ISSUE TITLE
"Upload to Azure Storage" with expanded folder uploads twice

### ISSUE THREAD

**Issue by EricJizbaMSFT** [microsoft/vscode-azurestorage#805]
Repro steps:
1. From the file view, expand a folder
1. Select that folder, its contents, and a file at the root level. Something like this:
    <img width="423" alt="Screen Shot 2020-09-14 at 11 12 26 AM" src="https://user-images.githubusercontent.com/11282622/93122432-4c50de80-f67b-11ea-91d7-e46e00437558.png">
1. Right click and upload to storage

Expected:
It uploads with the same folder structure as local

Actual:
The files inside "TimerTrigger1" are uploaded twice - once under a "TimerTrigger1" path and once at the root.
<img width="236" alt="Screen Shot 2020-09-14 at 11 13 59 AM" src="https://user-images.githubusercontent.com/11282622/93122521-7bffe680-f67b-11ea-9529-186d8ee4edb0.png">

**Comment by wwlorey** [comment]
The URIs passed into `uploadToAzureStorage` from a selection like that include the folder URI as well as each individual file because they were all selected. So the uploaded folder and files are accurate.

Changing this behavior would involve detecting when the selected files are the same as the children of the selected folder. And skipping the file uploads

**Comment by EricJizbaMSFT** [comment]
I wouldn't call this "accurate". Users don't care how VS Code gives us the uris (that's just an engineering detail). Plus - we're the ones picking the remote path, so we still have some control/blame here. I would model our behavior off of the local "Copy" experience within VS Code.
