### ISSUE TITLE
[Codespace] An error occurs when downloading a folder/file from blob container

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestorage#876]
**OS:** Win10
**Build Version:** Latest Release

**Repro Step:**
Download a folder/file from blob container.

**Expect:**
Download the folder/file successfully.

**Actual:**
An error occurs when downloading a folder/file from blob container.
![image](https://user-images.githubusercontent.com/57662131/97853549-34204600-1d33-11eb-8ec9-7c1bfe74f6d8.png)
Details in Output:
```
Downloading from "test001" to "/test001"...
Could not transfer "/test001"
Error: AzCopy Transfer: "Failed".
```
**More Info:**
This issue also reproduces for the file share.

**Comment by wwlorey** [comment]
It looks like you downloaded that file to the root directory. It makes sense that it failed because Codespaces doesn't give you admin rights to anything except the `home/codespaces` folder.

Downloading a file to a location in the `home/codespaces` folder works as expected
<img width="381" alt="Screen Shot 2020-11-09 at 2 05 57 PM" src="https://user-images.githubusercontent.com/22795803/98602054-b6a98800-2294-11eb-8b65-b66953cd55e1.png">
