### ISSUE TITLE
[Codespace] There is no file shows when trying uploading a file

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestorage#877]
**OS:** Win10
**Build Version:** Latest Release

**Repro Steps:**
1. Create a new Storage Account -> Create a blob container.
2. Right click the blob container -> Click "Upload Files...".
3. Check the result.

**Expect:**
The file shows in a dialog.

**Actual:**
There is no file shows.
![image](https://user-images.githubusercontent.com/57662131/97848605-48ad1000-1d2c-11eb-918e-7a88145f226a.png)

**Comment by wwlorey** [comment]
Related: https://github.com/microsoft/vscode/issues/110265

**Comment by jinglouMSFT** [comment]
I've tried this scenario. The experiences aren't optimal.

1. In a newly created storage account, created a blob container called "container1"
2. Right click on the blob container, then select "Upload Files..."
3. In the command palette, select the readme.md file from: codespace ➜ ~/workspace/node-todo (master)

Actual result: once the upload completed, readme.md did show up under the container "container1" node

Continue testing:
1. Right click on the "container1" node and select "Open in File Explorer"
2. In the command palette, select "Open in new window". This will launch another tab of VS Code Codespace in the browser and on the "container1" node will be displayed. 

Actual result: You will see the new tab "container1 [Codespaces] - Visual Studio Code - Insiders - Codespaces" like this:
![image](https://user-images.githubusercontent.com/10081483/100950092-78347100-34c0-11eb-9f24-ccfeb8819d09.png)

Clicking on the node "container1' shown as the last node in the above screenshot, you'll get the below error:
![image](https://user-images.githubusercontent.com/10081483/100950334-f8f36d00-34c0-11eb-802b-bf7ebb5927d3.png)

Remember that at this point, I already have the file "readme.md" uploaded into container "container1" as shown in the main Codespaces window:
![image](https://user-images.githubusercontent.com/10081483/100950634-9ea6dc00-34c1-11eb-9004-e71f526fcd45.png)

**Comment by jinglouMSFT** [comment]
BTW, this works as expected in normal VS Code with the storage extension. That is, the files are shown if i open in a new window.

**Comment by wwlorey** [comment]
> Actual result: once the upload completed, readme.md did show up under the container "container1" node

@jinglouMSFT As of right now it's by design to not show a blob that has just been uploaded (unless the blob container is already expanded). When you uploaded "readme.md" was "container1" expanded?

> Actual result: You will see the new tab "container1 [Codespaces] - Visual Studio Code - Insiders - Codespaces" like this:
> ![image](https://user-images.githubusercontent.com/22795803/101191679-d5d6d380-360e-11eb-9972-dd0c242f6ccc.png)

Codespaces' behavior with opening in file explorer is funky right now. It looks like you ran into a similar issue CTI filed in https://github.com/microsoft/vscode-azurestorage/issues/874. A VS Code bug on this has been filed in https://github.com/microsoft/vscode/issues/110352.

As for the original reason for this issue, which was not being able to select files to upload in Codespaces, it has been resolved (VS Code bug: https://github.com/microsoft/vscode/issues/110265). 
So this issue can be closed once we tie up any loose ends based on this comment.

**Comment by jinglouMSFT** [comment]
OK. my issue is different from what's originally in bug 877.  Created a new issue #898 for my part of the issue. 
#877 is considered fixed and closed.
