### ISSUE TITLE
Unable to choose Storage Account attributes, defaults to WESTUS (VS Code)

### ISSUE THREAD

**Issue by jeremyfiel** [microsoft/vscode-azurestorage#989]
Does this occur consistently? YES
Repro steps:

1. Sign in to Azure account from VS Code Azure Storage extension
2. Use + symbol to create new storage account
3. enter globally unique name
4. unable to select storage type, access tier, region etc.. >> defaults to westus and deploys standard v2 LRS, hot tier

I want the ability to select storage account options. At minimum, the region should be an option. Defaulting to WEST US is unexpected behavior and renders using the Azure tools useless for storage account creation if you're not in this region.

Version: 0.12.1
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.56.2
Language: en

**Comment by nturinski** [comment]
Hi @jeremyfiel 

If right-click your subscription or press F1 and search for `Azure Storage: Create Storage Account... (Advanced)` you should be able to set some of the properties that you mention in step 4.

We may want to move location to both creation commands since it is a pretty universally understood concept.
